PPSSTC/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PPSSTC.Indeces;
using PPSSTC.Models;
using PPSSTC.Models.ViewModels;
using Raven.Client;
using Raven.Client.Linq;
using System.Globalization;
using System.Text;
using PPSSTC.Helpers.CSV_Models;
using System.IO;
using ExcelDataReader;
using System.Data;

namespace PPSSTC.Controllers
{
    [Authorize]
    public class MembersController : RavenController
    {
        private int _pageSize = 15;

        public ActionResult Index(MemberListViewModel model)
        {
            model.Page = 1;

            var newViewModel = BuildViewmodel(model);

            return View(newViewModel);
        }

        public ActionResult Search(MemberListViewModel model)
        {
            var newViewModel = BuildViewmodel(model);

            return View("Index", newViewModel);
        }

        private MemberListViewModel BuildViewmodel(MemberListViewModel model)
        {
            model.PageSize = _pageSize;
            var members = BuildMemberQuery(model);

            RavenQueryStatistics stats;

            members = members.OrderBy(x => x.LastName).Statistics(out stats);

            var pagedMembers = members.As<Member>().Skip((model.Page - 1) * model.PageSize).Take(model.PageSize).ToList();

            model.Members = pagedMembers;

            model.TotalCount = stats.TotalResults;

            return model;
        }

        private IRavenQueryable<MembersIndex.MemberResult> BuildMemberQuery(MemberListViewModel model)
        {
            var userRole = Request.Cookies["role"].Value;
            var members = MemberSession.Query<MembersIndex.MemberResult, MembersIndex>();

            if (!string.IsNullOrEmpty(model.Name))
            {
                members = members.Search(x => x.Name, model.Name, escapeQueryOptions: EscapeQueryOptions.RawQuery);
            }

            if (model.Status != null)
            {
                members = (IRavenQueryable<MembersIndex.MemberResult>)members.Where(x => x.Status == model.Status);
            }

            if (model.Area != null)
            {
                members = (IRavenQueryable<MembersIndex.MemberResult>)members.Where(x => x.Area == model.Area);
            }

            if (model.SubArea != null)
            {
                members = (IRavenQueryable<MembersIndex.MemberResult>)members.Where(x => x.SubArea == model.SubArea);
            }

            if (model.Subspecialty != null)
            {
                members = (IRavenQueryable<MembersIndex.MemberResult>)members.Where(x => x.Subspecialty == model.Subspecialty);
            }

            if (model.Year.HasValue)
            {
                members = members.Where(x => x.paymentYears == null || x.paymentYears.Any(y => y != model.Year.Value));
            }

            if (userRole == "administrator")
            {
                // Only show not deleted members
                members = members.Where(x => !x.Deleted);
            }
            else
            {
                // Only show not deleted and alive members
                members = members.Where(x => !x.Deleted && !x.Deceased);
            }

            return members;
        }

        public ActionResult Add()
        {
            if (Request.Cookies.Get("role")
                .Value == "administrator")
            {
                var viewModel = new EditMemberModel { Member = new Member() };
                return View(viewModel);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Add(EditMemberModel model)
        {
            MemberSession.Store(model.Member);
            return RedirectToAction("Index");
        }

        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                id = HttpContext.Request.Cookies.Get("memberId").Value;
            }
            else
            {
                id = "members/" + id;
            }

            var member = MemberSession.Load<Member>(id);
            var cpdEvents = member.EventAttendance != null ? MemberSession.Load<CpdEvent>(member.EventAttendance).Where(x => x != null && !x.IsDeleted).ToList() : new List<CpdEvent>();
            var units = cpdEvents.Select(x => new CpdUnits { Date = x.Date, Name = x.Name, UnitType = x.CpdUnitType, Units = x.CpdCredits ?? (float?)null });

            var allUnits = new List<CpdUnits>();
            if (member.Units != null && member.Units.Count > 0)
            {
                allUnits.AddRange(member.Units);
            }
            allUnits.AddRange(units);

            // Join the two lists together. Member.units would have manually added credits

            var dictionary = allUnits != null ? allUnits.OrderByDescending(x => x.Date)
                                         .GroupBy(x => x.Date.Year + " - " + CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(x.Date.Month))
                                         .ToDictionary(key => key.Key, v => v.ToList())
                                         : null;


            return View(new MemberDetailViewModel
            {
                Member = member,
                CpdUnits = dictionary
            });
        }

        public ActionResult Edit(string id)
        {
            id = "members/" + id;
            var member = MemberSession.Load<Member>(id);
            var viewModel = new EditMemberModel();
            viewModel.Member = member;

            return View(viewModel);
        }

        public JsonResult AddPayment(string id, int? year)
        {
            var result = new GenericJsonResult();
            try
            {
                var member = MemberSession.Load<Member>(id);
                if (member.PaymentInfo == null)
                {
                    member.PaymentInfo = new List<PaymentInfo>();
                }
                if (member.PaymentInfo != null && member.PaymentInfo.Find(x => x.Year == year) == null)
                {
                    member.PaymentInfo.Add(new PaymentInfo { Year = year });
                }
                
                MemberSession.Store(member);

                result.Success = true;
                result.Message = "Successfully added payment information";
            }
            catch
            {
                result.Success = false;
                result.Message = "Unable to add payment information";
            }
            return Json(result);
        }

        [HttpPost]
        public ActionResult Delete(string id)
        {
            var user = MemberSession.Load<Member>(id);
            if (id != null && user != null)
            {
                user.Deleted = true;
                MemberSession.Store(user);
            }

            return RedirectToAction("Index");
        }

        public JsonResult AddCpdUnits(string id, DateTime date, string name, int units)
        {
            var result = new GenericJsonResult();
            try
            {
                var member = MemberSession.Load<Member>(id);
                if (member.Units == null)
                {
                    member.Units = new List<CpdUnits>();
                }

                var cpdUnit = new CpdUnits
                {
                    Date = date,
                    Name = name,
                    Units = units
                };

                member.Units.Add(cpdUnit);
                MemberSession.Store(member);

                result.Success = true;
                result.Message = "Successfully added CPD units";
            }
            catch
            {
                result.Success = false;
                result.Message = "Unable to add CPD units";
            }
            return Json(result);
        }

        [HttpPost]
        public ActionResult Edit(EditMemberModel model)
        {
            var oldMember = MemberSession.Load<Member>(model.Member.Id);

            MapToMember(model, oldMember);

            MemberSession.Store(oldMember);

            return RedirectToAction("Details", new { @id = oldMember.Id.Split('/')[1] });
        }

        public Helpers.CsvActionResult<PatientsCsvWrapper> ExportData(MemberListViewModel searchFilters)
        {
            var memberQuery = BuildMemberQuery(searchFilters);
            var page = 0;
            var pageSize = 100;
            var patients = new List<MemberCsvRow>();
            var keepGoing = true;
            do
            {
                var currentPatients = memberQuery.As<Member>().Skip(page * pageSize).Take(pageSize);
                if (currentPatients.FirstOrDefault() != null)
                {
                    patients.AddRange(currentPatients.Select(x =>
                    new MemberCsvRow
                    {
                        Area = x.Area,
                        Email = x.Email,
                        FirstName = x.FirstName,
                        LastName = x.LastName,
                        MiddleName = x.MiddleName,
                        MobileNumber = x.MobileNumber,
                        PhilHealth = x.PhilHealth,
                        PMA = x.PMA,
                        PRC = x.PRC,
                        Status = x.Status,
                        Subspecialty = x.Subspecialty,
                        DateDeceased = x.DateDeceased,
                        DateOfBirth = x.DateOfBirth
                    }));
                    page++;
                }
                else
                {
                    keepGoing = false;
                }
            } while (keepGoing);

            var patientsCsv = patients.Select(x => new PatientsCsvWrapper
            {
                Area = x.Area,
                Email = x.Email,
                FirstName = x.FirstName,
                LastName = x.LastName,
                MiddleName = x.MiddleName,
                MobileNumber = x.MobileNumber,

PPSSTC/Views/Members/Add.cshtml
@model PPSSTC.Models.ViewModels.EditMemberModel

@{
    ViewBag.Title = "title";
    Layout = "~/Views/_Layout.cshtml";
}


<div class="panel panel-default">
    <div class="panel-heading">
        <strong class="maroon">Add Member</strong>
    </div>
    @using (Html.BeginForm("Add", "Members", FormMethod.Post, new { @style = "max-width:650px;margin: 0 auto;" }))
    {
        @Html.HiddenFor(x => x.Member.Id)
        <div class="form-group" style="padding-top: 20px">
            <label>First Name</label>
            @Html.TextBoxFor(x => x.Member.FirstName, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Middle Name</label>
            @Html.TextBoxFor(x => x.Member.MiddleName, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Last Name</label>
            @Html.TextBoxFor(x => x.Member.LastName, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Year inducted at PPSSTC</label>
            @Html.TextBoxFor(x => x.Member.YearInducted, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>PRC Number</label>
            @Html.TextBoxFor(x => x.Member.PRC, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>PMA Number</label>
            @Html.TextBoxFor(x => x.Member.PMA, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Philhealth Accreditation Number</label>
            @Html.TextBoxFor(x => x.Member.PhilHealth, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Status</label>
            @Html.DropDownListFor(x => x.Member.Status, Model.GetStatuses(), new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Subspecialty</label>
            @Html.DropDownListFor(x => x.Member.Subspecialty, Model.GetSubspecialties(), new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Area</label>
            @Html.DropDownListFor(x => x.Member.Area, Model.GetAreas(), new { @class = "form-control", @id = "areaDropdown" })
        </div>

        <div class="form-group">
            <label>Subarea</label>
            @Html.DropDownListFor(x => x.Member.SubArea, Model.GetSubAreas(Model.Member.Area), new { @class = "form-control", @id = "subAreaDropdown" })
        </div>

        <div class="form-group">
            <label>Date of Birth</label>
            @Html.TextBoxFor(x => x.Member.DateOfBirth, new { @class = "form-control", @type = "date" })
        </div>

        <div class="form-group" style="padding-top: 20px">
            <label for="deceasedCheckBox" style="padding-right: 5px">Deceased</label>
            @Html.CheckBoxFor(x => x.Member.Deceased, new { @style = "vertical-align: top;", @id = "deceasedCheckBox" })
        </div>

        <div class="form-group" id="deceasedDateDiv">
            <label>Date of Death</label>
            @Html.TextBoxFor(x => x.Member.DateDeceased, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Email</label>
            @Html.TextBoxFor(x => x.Member.Email, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Mobile</label>
            @Html.TextBoxFor(x => x.Member.MobileNumber, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Masteral and Post Graduate Courses (Academic and Non Academic) and Others</label>
            @Html.TextAreaFor(x => x.Member.Comments, new { @class = "form-control" })
        </div>

        <div class="form-group" style="text-align: center">
            <button type="submit" class="btn btn-default">Add</button>
        </div>

    }
</div>
<script>
    $(function () {
        $("#deceasedDateDiv").hide();

        $("#deceasedCheckBox").change(function () {
            var isDeceased = $(this).is(":checked");

            if (isDeceased) {
                $("#deceasedDateDiv").show();
            }
            else {
                $("#deceasedDateDiv").hide();
            }
        });

        $("#areaDropdown").change(function () {
            var areaValue = $(this).val();

            var subAreas = getSubAreas(areaValue);
            console.log(subAreas);

            var subAreaDropDown = subAreas.map(subArea => {
                return $("<option></option>").val(subArea.value).prop("selected", subArea.selected).text(subArea.text);
            });

            $("#subAreaDropdown").html(subAreaDropDown);
        });

        function getSubAreas(area) {
            var subAreas = [];

            if (area == "Laguna_MLP") {
                subAreas = 
                [
                    { text: "Laguna Proper", value: "Laguna_Proper", selected: true },
                    { text: "Muntinlupa", value: "Muntinlupa", selected: false },
                    { text: "Las Pinas", value: "Las_Pinas", selected: false },
                    { text: "Paranaque", value: "Paranaque", selected: false }
                ];
            }
            else if (area == "Island_Provinces") {
                subAreas = 
                [
                    { text: "Oriental Mindoro", value: "Oriental_Mindoro", selected: true },
                    { text: "Occidental Mindoro", value: "Occidental_Mindoro", selected: false },
                    { text: "Marinduque", value: "Marinduque", selected: false},
                    { text: "Romblon", value: "Romblon", selected: false },
                    { text: "Palawan", value: "Palawan", selected: false },
                ];
            }
            else {
                subAreas = 
                [
                    { text: "No subarea/s available", value: null, selected: true },
                ];
            }
            return subAreas;
        }
    });
</script>

PPSSTC/Views/Members/Details.cshtml
@model PPSSTC.Models.ViewModels.MemberDetailViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_Layout.cshtml";
}
<style>
    strong {
        display: block;
    }

    .memberSpan {
        display: block;
        padding-bottom: 10px;
    }
</style>
@{
    var loggedinUserOrAdmin = (Request.Cookies["memberId"] != null && Request.Cookies["memberId"].Value.Equals(Model.Member.Id)) || (HttpContext.Current.Request.Cookies.Get("role") != null && HttpContext.Current.Request.Cookies.Get("role").Value == "administrator");
}
<div class="page-header" style="text-align: center">
    <h1 class="maroon">@Model.Member.LastName, @Model.Member.FirstName @Model.Member.MiddleName</h1>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
       <strong class="maroon"><i class="fa fa-user" aria-hidden="true"></i> Member Information</strong>
    </div>
    <div class="panel-body">
        <span class="memberSpan"><strong>Year inducted at PPSSTC:</strong>@Model.Member.YearInducted</span>
        <span class="memberSpan"><strong>PRC:</strong>@Model.Member.PRC</span>
        <span class="memberSpan"><strong>PMA:</strong>@Model.Member.PMA</span>
        <span class="memberSpan"><strong>PhilHealth:</strong>@Model.Member.PhilHealth</span>
        <span class="memberSpan"><strong>Status:</strong>@Model.Member.Status.ToString().Replace("_", " ")</span>
        <span class="memberSpan"><strong>Subspecialty:</strong>@Model.Member.Subspecialty.ToString().Replace("_", " ")</span>
        <span class="memberSpan"><strong>Area:</strong>@Model.Member.AreaToReadableString(Model.Member.Area)</span>
        <span class="memberSpan"><strong>Subarea:</strong>@(Model.Member.SubArea == null ? "N/A" : Model.Member.SubArea.ToString().Replace("_", " "))</span>
        <span class="memberSpan"><strong>Date of Birth:</strong>@(Model.Member.DateOfBirth != DateTime.MinValue ? Model.Member.DateOfBirth.ToShortDateString() : "")</span>
        <span class="memberSpan" id="dateOfDeathTxt"><strong>Date of Death:</strong>@Model.Member.DateDeceased</span>
        <span class="memberSpan"><strong>Email:</strong>@Model.Member.Email</span>
        <span class="memberSpan"><strong>Mobile Number:</strong>@Model.Member.MobileNumber</span>
        <span class="memberSpan"><strong>Masteral and Post Graduate Courses (Academic and Non Academic) and Others:</strong>@Model.Member.Comments</span>
        @if (loggedinUserOrAdmin)
        {
            <a type="button" class="btn btn-danger navbar-btn" href="@Url.Action("Edit", new { @id = Model.Member.Id.Split('/')[1] })">Edit</a>
        }
    </div>
</div>

@if (loggedinUserOrAdmin) { 
    <div class="panel panel-default">
    <div class="panel-heading">
        <strong class="maroon"><i class="fa fa-calendar" aria-hidden="true"></i> CPD Credits</strong>
    </div>
    <div class="panel-body">
        @{var lastyear = 0;}
        @if (Model.CpdUnits != null && Model.CpdUnits.Any())
        { 
            foreach (var cpdUnit in Model.CpdUnits)
            {

                {
                    float total = 0;
                    // First will always work because of groupby
                    var currentyear = cpdUnit.Value.First().Date.Year;


                    if (currentyear != lastyear)
                    {
                        lastyear = currentyear;
                        <h4>@currentyear</h4>
                    }
                    <span><b>@cpdUnit.Key.Substring(7)</b></span><br/>
                    foreach (var units in cpdUnit.Value)
                    {
                        <span>@units.Name - @(units.UnitType == PPSSTC.Models.CpdUnitType.Units ? units.Units.ToString() : Model.GetSelectedCpdUnitType(units.UnitType))</span><br/>
                        total += units.UnitType == PPSSTC.Models.CpdUnitType.Units && units.Units.HasValue ? units.Units.Value : 0;

                    }
                <span>Total - @total</span><br/><br/>
                }
            }
        }else{
            <h4>No CPD credits on record</h4>
        }
        
    </div>
</div>
}

@if (loggedinUserOrAdmin)
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong class="maroon"><i class="fa fa-money" aria-hidden="true"></i> Payment History</strong>
        </div>
        <div class="panel-body">
            @if (Model.Member.PaymentInfo != null && Model.Member.PaymentInfo.Any())
            {
                <h4>Paid for the following years</h4>
                <ul>
                    @foreach (var info in Model.Member.PaymentInfo.OrderByDescending(y => y.Year))
                    {
                    <li>
                        <strong>@(info.Year == null ? "exempted" : info.Year.ToString())</strong>
                    </li>
                    }
                </ul>
            }
            else
            { 
                <h4>No payment history on record</h4>
            }
        </div>
    </div>
}
<script>
    $(function () {
        var isDeceased = ("@Model.Member.Deceased" == 'True');
        console.log(isDeceased);
        if (isDeceased) {
            $("#dateOfDeathTxt").show();
        }
        else {
            $("#dateOfDeathTxt").hide();
        }
    });
</script>

PPSSTC/Views/Members/Edit.cshtml
@model PPSSTC.Models.ViewModels.EditMemberModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/_Layout.cshtml";
}
@using PPSSTC

<div class="panel panel-default">
    <div class="panel-heading">
        <strong class="maroon">Member Information</strong>
    </div>
    @using (Html.BeginForm("Edit", "Members", FormMethod.Post, new { @style = "max-width:650px;margin: 0 auto;" }))
    {
        @Html.HiddenFor(x => x.Member.Id)
        <div class="form-group" style="padding-top:20px">
            <label>First Name</label>
            @Html.TextBoxFor(x => x.Member.FirstName, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Middle Name</label>
            @Html.TextBoxFor(x => x.Member.MiddleName, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Last Name</label>
            @Html.TextBoxFor(x => x.Member.LastName, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Year inducted at PPSSTC</label>
            @Html.TextBoxFor(x => x.Member.YearInducted, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>PRC Number</label>
            @Html.TextBoxFor(x => x.Member.PRC, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>PMA Number</label>
            @Html.TextBoxFor(x => x.Member.PMA, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Philhealth Accreditation Number</label>
            @Html.TextBoxFor(x => x.Member.PhilHealth, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Status</label>
            @Html.DropDownListFor(x => x.Member.Status, Model.GetStatuses(), new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Subspecialty</label>
            @Html.DropDownListFor(x => x.Member.Subspecialty, Model.GetSubspecialties(), new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Area</label>
            @Html.DropDownListFor(x => x.Member.Area, Model.GetAreas(), new { @class = "form-control", @id = "areaDropdown" })
        </div>

        <div class="form-group">
            <label>Subarea</label>
            @Html.DropDownListFor(x => x.Member.SubArea, Model.GetSubAreas(Model.Member.Area), new { @class = "form-control", @id = "subAreaDropdown" })
        </div>

        <div class="form-group">
            <label>Date of Birth</label>
            @Html.TextBoxFor(x => x.Member.DateOfBirth, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
        </div>

        <div class="form-group" style="padding-top: 20px">
            <label for="deceasedCheckBox" style="padding-right: 5px">Deceased</label>
            @Html.CheckBoxFor(x => x.Member.Deceased, new { @style = "vertical-align: top;", @id = "deceasedCheckBox" })
        </div>

        <div class="form-group" id="deceasedDateDiv">
            <label>Date of Death</label>
            @Html.TextBoxFor(x => x.Member.DateDeceased, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Email</label>
            @Html.TextBoxFor(x => x.Member.Email, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Mobile</label>
            @Html.TextBoxFor(x => x.Member.MobileNumber, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Masteral and Post Graduate Courses (Academic and Non Academic) and Others</label>
            @Html.TextAreaFor(x => x.Member.Comments, new { @class = "form-control" })
        </div>
        <div class="form-group" style="text-align:center">
            <button type="submit" class="btn btn-danger">Save Changes</button>
        </div>
    }
</div>
<script>
    $(function () {
        var isDeceased = $("#deceasedCheckBox").is(":checked");

        if (isDeceased) {
            $("#deceasedDateDiv").show();
        }
        else {
            $("#deceasedDateDiv").hide();
        }

        $("#deceasedCheckBox").change(function () {
            var isDeceased = $(this).is(":checked");

            if (isDeceased) {
                $("#deceasedDateDiv").show();
            }
            else {
                $("#deceasedDateDiv").hide();
            }
        });

        $("#areaDropdown").change(function () {
            var areaValue = $(this).val();

            var subAreas = getSubAreas(areaValue);
            console.log(subAreas);

            var subAreaDropDown = subAreas.map(subArea => {
                return $("<option></option>").val(subArea.value).prop("selected", subArea.selected).text(subArea.text);
            });

            $("#subAreaDropdown").html(subAreaDropDown);
        });

        function getSubAreas(area) {
            var subAreas = [];

            if (area == "Laguna_MLP") {
                subAreas =
                    [
                        { text: "Laguna Proper", value: "Laguna_Proper", selected: true },
                        { text: "Muntinlupa", value: "Muntinlupa", selected: false },
                        { text: "Las Pinas", value: "Las_Pinas", selected: false },
                        { text: "Paranaque", value: "Paranaque", selected: false }
                    ];
            }
            else if (area == "Island_Provinces") {
                subAreas =
                    [
                        { text: "Oriental Mindoro", value: "Oriental_Mindoro", selected: true },
                        { text: "Occidental Mindoro", value: "Occidental_Mindoro", selected: false },
                        { text: "Marinduque", value: "Marinduque", selected: false },
                        { text: "Romblon", value: "Romblon", selected: false },
                        { text: "Palawan", value: "Palawan", selected: false },
                    ];
            }
            else {
                subAreas =
                    [
                        { text: "No subarea/s available", value: null, selected: true },
                    ];
            }
            return subAreas;
        }
    });
</script>

PPSSTC/Views/Members/UploadResults.cshtml
@model PPSSTC.Models.MemberUploadResult
@{
    Layout = "~/Views/_Layout.cshtml";
}

<div class="panel panel-default" style="text-align: center">
    @if (string.IsNullOrEmpty(Model.Error) && !Model.FailedUploads.Any())
    {
        <h1 style="margin: 0 auto; padding: 30px;">Upload completed successfully</h1>
        <label>@Model.SuccessfulUploads were successfully added</label> <br />

        <a href="@Url.Action("Index")" class="btn btn-default" style="margin:20px;">Back to Members</a>
    }

    @if (!string.IsNullOrEmpty(Model.Error))
    {
        <h1 style="margin: 0 auto; padding: 30px;">An error occurred</h1>
        <label>@Model.Error</label> <br />
        <label>To try again press back on your browser and try again.</label>
    }

    @if (Model.FailedUploads != null)
    {
        if (Model.FailedUploads.Any())
        {
            <h1 style="margin: 0 auto; padding: 30px;">Upload partially completed</h1>
            <label>@Model.SuccessfulUploads were successfully added</label> <br />

            <label>The following were not successfully uploaded</label> <br />
            <ul>
                @foreach (var error in Model.FailedUploads)
                {
                    <li>
                        @error
                    </li>
                }
            </ul>
        }
    }
</div>