PPSSTC/Controllers/StaticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PPSSTC.Controllers
{
    public class StaticController : Controller
    {
        //
        // GET: /Static/



        public ActionResult Diagnosis()
        {
            return View();
        }


        public ActionResult TreatmentOutcomes()
        {
            return View();
        }

        public ActionResult AdverseDrugReactions()
        {
            return View();
        }

    }
}

PPSSTC/Controllers/TbRegistryController.cs
using PPSSTC.Indeces;
using PPSSTC.Models;
using PPSSTC.Models.ViewModels;
using Raven.Client;
using Raven.Client.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace PPSSTC.Controllers
{
    [Authorize]
    public class TbRegistryController : RavenController
    {
        private int _pageSize = 15;

        public ActionResult Index(TbListViewModel model)
        {
            model.Page = 1;

            var newViewModel = BuildViewmodel(model);

            return View(newViewModel);
        }

        public ActionResult Delete(string id)
        {
            var user = MemberSession.Load<TbPatient>(id);
            if (id != null && user != null)
            {
                user.Deleted = true;
                MemberSession.Store(user);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Edit(string id)
        {
            var ravenId = "TbPatients/" + id;
            var patient = MemberSession.Load<TbPatient>(ravenId);
            var viewModel = new TbPatientViewModel { 
            Patient = patient
            };

            return View(viewModel);
        }

        public ActionResult Details(string id)
        {
            var ravenId = "TbPatients/" + id;
            var patient = MemberSession.Load<TbPatient>(ravenId);
            var viewModel = new TbPatientViewModel
            {
                Patient = patient
            };

            return View(viewModel);
        }

        public Helpers.CsvActionResult<TbPatient> ExportData()
        {
            var page = 0;
            var pageSize = 100;
            var patients = new List<TbPatient>();
            var keepGoing = true;
            do
            {
                var currentPatients = MemberSession.Query<TbPatient>().Skip(page * pageSize).Take(pageSize);
                if (currentPatients.Any())
                {
                    patients.AddRange(currentPatients);
                    page++;
                }
                else {
                    keepGoing = false;
                }
            } while (keepGoing);

            var headers = "First Name,Middle Name,Last Name,Age,Birthday,Gender,Residence,Residence if Other,Comments,Exposure,Exposure if yes,Disease Onset,Persistent cough/wheezing of 2 weeks or more,Unexplained fever (>38C) or 2 weeks or more,Loss of appetite or failure to gain weight,Failure to repsond to 2 weeks of appropriate antibiotic therapy for lower respiratory tract infection,Failure to regain previous state of health 2 weeks after viral infection or exanthem,Fatigure or reduced playfulness or lethargy,Abdominal swellings, hard painless mass and free fluid,Boint or Join Lesions,Cns Symptoms,Skintest,Xray,Xray if with comments,Direct Spectrum Smear Microscopy,Other Diagnostics,Start of Treatment,End of Treatment,Treatment,Treatment if others,Treatment Outcome,Adverse Drug Reactions,Reported to the government?";
            var stringBuilder = new StringBuilder();

            var result = new Helpers.CsvActionResult<TbPatient>(patients, "TBRegistryExport.csv");
            return result;
        }

        [HttpPost]
        public ActionResult Edit(TbPatientViewModel model)
        {
            MemberSession.Store(model.Patient);
            return RedirectToAction("Index");
        }

        public ActionResult Add()
        {
            var viewModel = new TbPatientViewModel {Patient = new TbPatient() };
            var role = HttpContext.Request.Cookies.Get("role").Value;
            if (role.Equals("member"))
            {
                var memberId = HttpContext.Request.Cookies.Get("memberId").Value;
                var member = MemberSession.Load<Member>(memberId);
                viewModel.Patient.DoctorId = member.Id;
                viewModel.Patient.DoctorName = member.FirstName + " " + member.LastName;
            }
            else {
                var username = "Administrator";
                if (HttpContext.Request.Cookies.Get("username") != null) {
                    username = HttpContext.Request.Cookies.Get("username").Value;
                }
                viewModel.Patient.DoctorName = username;
            }

            viewModel.Patient.StartDate = DateTime.Now;
            viewModel.Patient.Birthday = DateTime.Now;
            viewModel.Patient.Xray = Xray.Notdone;
            viewModel.Patient.Skintest = SkinTest.NotDone;
            viewModel.Patient.TreatmentOutcome = TreatmentOutcome.OnGoing;
            viewModel.Patient.DirectSpectrumSmear = DirectSpectrumSmear.NotDone;
            viewModel.Patient.Government = Government.No;

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(TbPatientViewModel model)
        {
            MemberSession.Store(model.Patient);
            return RedirectToAction("Index");
        }

        public ActionResult Search(TbListViewModel model)
        {
            var newViewModel = BuildViewmodel(model);

            return View("Index", newViewModel);
        }

        private TbListViewModel BuildViewmodel(TbListViewModel model)
        {
            model.PageSize = _pageSize;
            var members = MemberSession.Query<TbRegistryIndex.TbRegistryResult, TbRegistryIndex>();

            members = members.Where(x => !x.Deleted);

            if (!string.IsNullOrEmpty(model.Name))
            {
                members = members.Search(x => x.Name, model.Name, escapeQueryOptions: EscapeQueryOptions.RawQuery);
            }

            RavenQueryStatistics stats;

            members = members.OrderBy(x => x.LastName).Statistics(out stats);

            var pagedMembers = members.As<TbPatient>().Skip((model.Page - 1) * model.PageSize).Take(model.PageSize).ToList();

            model.Patients = pagedMembers;

            model.TotalCount = stats.TotalResults;

            return model;
        }
    }
}

PPSSTC/Views/TbRegistry/Add.cshtml
@model PPSSTC.Models.ViewModels.TbPatientViewModel

@{
    ViewBag.Title = "title";
    Layout = "~/Views/_Layout.cshtml";
}
<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
@using (Html.BeginForm("Add", "TbRegistry", FormMethod.Post, new { @style = "margin: 0 auto;" }))
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong class="maroon">Demographics</strong>
        </div>
        <div style="max-width: 650px; margin: 0 auto;">
            @Html.HiddenFor(x => x.Patient.Id)
            <div class="form-group" style="padding-top: 20px">
                <label>First Name</label>
                @Html.TextBoxFor(x => x.Patient.FirstName, true, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Patient.FirstName)
            </div>
            <div class="form-group" style="padding-top: 20px">
                <label>Middle Name</label>
                @Html.TextBoxFor(x => x.Patient.MiddleName, new { @class = "form-control" })
            </div>
            <div class="form-group" style="padding-top: 20px">
                <label>Last Name</label>
                @Html.TextBoxFor(x => x.Patient.LastName, true, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Patient.LastName)
            </div>
            <div class="form-group" style="padding-top: 20px">
                <label>Age</label>
                @Html.TextBoxFor(x => x.Patient.Age, true, null, new { @class = "form-control", @id = "age" })
                @Html.ValidationMessageFor(x => x.Patient.Age)
            </div>
            <div class="form-group" style="padding-top: 20px">
                <label>Birthday</label>
                @Html.TextBoxFor(x => x.Patient.Birthday, true, null, new { @class = "form-control", @id = "birthday" })
                @Html.ValidationMessageFor(x => x.Patient.Birthday)
            </div>
            <div class="form-group" style="padding-top: 20px">
                <label>Gender</label>
                @Html.DropDownListFor(x => x.Patient.Gender, Model.GetGender(), new { @class = "form-control" })
            </div>
            <div class="form-group" style="padding-top: 20px">
                <label>Residence</label>
                @Html.DropDownListFor(x => x.Patient.Residence, Model.GetArea(), new { @class = "form-control", @id = "residence" })
            </div>

            <div class="form-group" style="padding-top: 20px; display: none" id="residenceTextDiv">
                <label>Residence - Other</label>
                @Html.TextBoxFor(x => x.Patient.ResidenceText, new { @class = "form-control", @id = "residenceText" })
            </div>

            <div class="form-group" style="padding-top: 20px">
                <label>Attending Physician</label>
                @Html.HiddenFor(x => x.Patient.DoctorId)
                @Html.TextBoxFor(x => x.Patient.DoctorName, new { @class = "form-control", @readonly = "readonly" })
            </div>
            <div class="form-group" style="padding-top: 20px">
                <label>Comments</label>
                @Html.TextAreaFor(x => x.Patient.Comments, new { @class = "form-control" })
            </div>
        </div>
    </div>
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong class="maroon">History</strong>
        </div>
        <div style="max-width: 650px; margin: 0 auto;">
            <div class="form-group" style="padding-top: 20px">
                <label>Exposure</label>
                @Html.DropDownListFor(x => x.Patient.Exposure, Model.GetExposure(), new { @class = "form-control", @id = "exposure" })
            </div>
            <div class="form-group" style="padding-top: 20px; display: none" id="exposureTextDiv">
                <label>If yes, please specify</label>
                @Html.TextBoxFor(x => x.Patient.ExposureText, new { @class = "form-control", @id = "exposureText" })
            </div>


            <div class="form-group" style="padding-top: 20px">
                <label>Disease onset</label>
                @Html.TextBoxFor(x => x.Patient.DiseaseOnset, new { @class = "form-control", @id = "diseaseOnset" })
            </div>
        </div>
    </div>
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong class="maroon">Symptoms</strong>
        </div>
        <div style="max-width: 650px; margin: 0 auto;">
            <div class="form-group" style="padding-top: 20px">
                @Html.CheckBoxFor(x => x.Patient.Cough, new { @style = "vertical-align: top;" })
                <label style="font-weight: inherit">Persistent cough/wheezing of 2 weeks or more</label>
            </div>
            <div class="form-group" style="padding-top: 20px">
                @Html.CheckBoxFor(x => x.Patient.Fever, new { @style = "vertical-align: top;" })
                <label style="font-weight: inherit">Unexplained fever (>38C) or 2 weeks or more</label>
            </div>
            <div class="form-group" style="padding-top: 20px">

                @Html.CheckBoxFor(x => x.Patient.LossOfAppetite, new { @style = "vertical-align: top;" })
                <label style="font-weight: inherit">Loss of appetite or failure to gain weight</label>
            </div>
            <div class="form-group" style="padding-top: 20px">
                @Html.CheckBoxFor(x => x.Patient.FailureToRespondToAntibiotics, new { @style = "vertical-align: top;" })
                <label style="font-weight: inherit">Failure to repsond to 2 weeks of appropriate antibiotic therapy for lower respiratory tract infection</label>
            </div>
            <div class="form-group" style="padding-top: 20px">

                @Html.CheckBoxFor(x => x.Patient.FailureToRegainStateOfHealth, new { @style = "vertical-align: top;" })
                <label style="font-weight: inherit">Failure to regain previous state of health 2 weeks after viral infection or exanthem</label>
            </div>
            <div class="form-group" style="padding-top: 20px">

                @Html.CheckBoxFor(x => x.Patient.Fatigue, new { @style = "vertical-align: top;" })
                <label style="font-weight: inherit">Fatigue or reduced playfulness or lethargy</label>
            </div>
            <div class="form-group" style="padding-top: 20px">
                @Html.CheckBoxFor(x => x.Patient.AbnominalSwelling, new { @style = "vertical-align: top;" })
                <label style="font-weight: inherit">Abdominal swellings, hard painless mass and free fluid</label>
            </div>
            <div class="form-group" style="padding-top: 20px">
                @Html.CheckBoxFor(x => x.Patient.BoneOrJointLesions, new { @style = "vertical-align: top;" })
                <label style="font-weight: inherit">Boint or Join Lesions</label>
            </div>
            <div class="form-group" style="padding-top: 20px">
                @Html.CheckBoxFor(x => x.Patient.CnsSymptoms, new { @style = "vertical-align: top;" })
                <label style="font-weight: inherit">CNS Symptoms</label>
            </div>
        </div>
    </div>
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong class="maroon">Diagnostics</strong>
        </div>
        <div style="max-width: 650px; margin: 0 auto;">
            <div class="form-group" style="padding-top: 20px">
                <label>Skin test</label>
                @Html.DropDownListFor(x => x.Patient.Skintest, Model.GetSkinTests(), new { @class = "form-control" })
            </div>
            <div class="form-group" style="padding-top: 20px">
                <label>Xray</label>
                @Html.DropDownListFor(x => x.Patient.Xray, Model.GetChestXray(), new { @class = "form-control", @id = "xray" })
            </div>
            <div class="form-group" style="padding-top: 20px; display: none" id="xrayTextDiv">
                <label>If others, please specify</label>
                @Html.TextBoxFor(x => x.Patient.XrayText, new { @class = "form-control", @id = "xrayText" })
            </div>

            <div class="form-group" style="padding-top: 20px">
                <label>Direct Spectrum Smear Microscopy</label>
                @Html.DropDownListFor(x => x.Patient.DirectSpectrumSmear, Model.GetDirectSputumSmearMicroscopy(), new { @class = "form-control" })
            </div>
            <div class="form-group" style="padding-top: 20px">
                <label>Other Diagnostics</label>
                @Html.TextAreaFor(x => x.Patient.OtherDiagnostics, new { @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <strong class="maroon">Diagnosis <a href="@Url.Action("diagnosis","static")" target="_blank">[?]</a></strong>
        </div>
        <div style="max-width: 650px; margin: 0 auto;">
           <div class="form-group" style="padding-top: 20px">
                <label>Diagnosis:</label> TB Disease 
            </div>
        </div>
    </div>  
        
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong class="maroon">Treatment</strong>
        </div>
        <div style="max-width: 650px; margin: 0 auto;">
            <div class="form-group" style="padding-top: 20px">
                <label>StartDate</label>
                @Html.TextBoxFor(x => x.Patient.StartDate, new { @class = "form-control", @id = "startDate" })
            </div>
            <div class="form-group" style="padding-top: 20px">
                <label>End Date</label>
                @Html.TextBoxFor(x => x.Patient.EndDate, new { @class = "form-control", @readOnly = "readOnly", @id = "endDate" })
            </div>
            <div class="form-group" style="padding-top: 20px">
                <label>Treatment</label>
                @Html.DropDownListFor(x => x.Patient.Treatment, Model.GetTreatment(), new { @class = "form-control", @id = "treatment" })
            </div>
            <div class="form-group" style="padding-top: 20px; display: none" id="treatmentTextDiv">
                <label>If others, please specify</label>
                @Html.TextBoxFor(x => x.Patient.Treatmenttext, new { @class = "form-control", @id = "treatmentText" })
            </div>

            <div class="form-group" style="padding-top: 20px">
                <label>Treatment Outcome <a href="@Url.Action("treatmentoutcomes","static")" target="_blank">[?]</a></label>
                @Html.DropDownListFor(x => x.Patient.TreatmentOutcome, Model.GetTreatmentOutcomes(), new { @class = "form-control" })
            </div>
            <div class="form-group" style="padding-top: 20px">
                <label>If with advesrse drug reaction, please indicate the symptom or reaction and its onset</label>
                @Html.TextAreaFor(x => x.Patient.AdverseDrugReactions, new { @class = "form-control" })
            </div>
            <div class="form-group" style="padding-top: 20px">
                <label>Reported to the government?</label>
                @Html.DropDownListFor(x => x.Patient.Government, Model.GetGovernment(), new { @class = "form-control" })
            </div>
        </div>
    </div>
    
    <div class="form-group" style="text-align: center">
        <button type="submit" class="btn btn-danger">Add</button>
    </div>
}

<script>
    $(function () {
        $("#startDate").val('');
        $("#birthday").val('');
        $("#diseaseOnset").val('');
        $("#endDate").val('');
        $("#startDate").datepicker({
            changeYear: true,
            yearRange: "1990:2020"
        });
        $("#birthday").datepicker({
            changeYear: true,
            yearRange: "1990:2020"
        });
        $("#diseaseOnset").datepicker({
            changeYear: true,
            yearRange: "1990:2020"
        });
        $("#age").val('');
    });

    $("#startDate").on("change", function (e) {
        var val = $("#startDate").datepicker("getDate");
        var endDate = new Date(new Date(val).setMonth(val.getMonth() + 6));
        var dd = endDate.getDate();
        var mm = endDate.getMonth() + 1;//January is 0! 
        var yyyy = endDate.getFullYear();
        if (dd < 10) { dd = '0' + dd }
        if (mm < 10) { mm = '0' + mm }
        $("#endDate").val(mm + '/' + dd + '/' + yyyy);
    });

    $("#exposure").on("change", function (e) {
        var newValue = $("#exposure").val();
        if (newValue == "True") {
            $("#exposureTextDiv").show();
        } else {
            $("#exposureTextDiv").hide();
            $("#exposureText").val('');
        }
    });

    $("#residence").on("change", function (e) {
        var newValue = $("#residence").val();
        if (newValue == "Others") {
            $("#residenceTextDiv").show();
        } else {
            $("#residenceTextDiv").hide();
            $("#residenceText").val('');
        }
    });

    $("#xray").on("change", function (e) {
        var newValue = $("#xray").val();
        if (newValue == "Others") {
            $("#xrayTextDiv").show();
        } else {
            $("#xrayTextDiv").hide();
            $("#xrayText").val('');
        }
    });

    $("#treatment").on("change", function (e) {
        var newValue = $("#treatment").val();
        if (newValue == "Others") {
            $("#treatmentTextDiv").show();
        } else {
            $("#treatmentTextDiv").hide();
            $("#treatmentText").val('');
        }
    });
</script>

PPSSTC/Views/TbRegistry/Index.cshtml
@model PPSSTC.Models.ViewModels.TbListViewModel

@{
    ViewBag.Title = "TB Registry";
    Layout = "~/Views/_Layout.cshtml";
}
<style>
    @@media (max-width: 991px) {
        .mobile {
            display: none !important;
        }
    }

     @@media (max-width: 990px) {
        .smallonly {
            display: inline !important;
        }
    }

    .searchBox {
        margin: 0 auto;
        max-width: 900px;
    }
</style>
<div class="page-header">
    <div class="jumbotron" style="text-align: center">
        <div class="container">
            <div class="container">
                <img src="~/css/images/hero.png" class="mobile" />
                <img src="~/css/images/herotall.png" style="display:none" class="smallonly" />
                <p>Some helpful links</p>
                <p><a type="button" class="btn btn-primary" style="display: inline" href="@Url.Action("Add", "TbRegistry")">Add new record to the registry</a> <a type="button" class="btn btn-primary" style="display: inline" target="_blank" href="@Url.Action("Diagnosis", "Static")">How to diagnose TB Patients</a>  <a type="button" class="btn btn-primary" style="display: inline" target="_blank"href="@Url.Action("TreatmentOutcomes", "Static")">Possible treatment outcomes</a></p>
            </div>
        </div>
    </div>

    <div class="searchBox">
        <div class="container">
            @using (Html.BeginForm("Search", "TbRegistry", FormMethod.Get, new { @id = "searchForm", @style = "max-width:900px;padding-left: 0px; padding-right: 0px" }))
            {
                @Html.HiddenFor(x => x.Page, new { @id = "page" })
                <div class="row">
                    <div class="col-md-11">
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control", @placeHolder = "Name" })
                    </div>
                    <div class="col-md-1">
                        <button class="btn btn-danger" style="float: right">Search</button>
                    </div>
                </div>
            }

            <a type="button" class="btn" style="display: inline" href="@Url.Action("Add", "TbRegistry")">Add new record</a>
             @if (HttpContext.Current.Request.Cookies.Get("role") != null && HttpContext.Current.Request.Cookies.Get("role")
                            .Value == "administrator")
                        {
            <a type="button" class="btn" style="display: inline" href="@Url.Action("Exportdata", "TbRegistry")">Export data</a>
             }
        </div>
    </div>
</div>

<div id="notifications">
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <strong class="maroon">TB Registry</strong>
    </div>
    <div class="panel-body">
        <div class="container-fluid">
            <div class="row mobile">
                <div class="col-md-9"><strong>Name</strong></div>
                <div class="col-md-3"></div>
            </div>
            @if (Model.Patients != null && Model.Patients.Any())
            {
                foreach (var patient in Model.Patients)
                {
                <div class="row rowdata">
                    <div class="col-md-9">@patient.LastName, @patient.FirstName @patient.MiddleName</div>
                    <div class="col-md-3">
                        <a type="button" class="btn" style="display: inline" href="@Url.Action("Details", "TbRegistry", new { @id = patient.Id.Split('/')[1] })">View</a>
                        <a type="button" class="btn" style="display: inline" href="@Url.Action("Edit", "TbRegistry", new { @id = patient.Id.Split('/')[1] })">Edit</a>
                        <a type="button" class="btn delete" style="display: inline" href="#" data-name="@patient.LastName, @patient.FirstName @patient.MiddleName" data-id="@patient.Id">Delete</a>
                    </div>
                </div>
            
                }
                <div class="row">
                    <div class="col-md-12" style="text-align: center">
                        @{
                var start = Model.Page != 1 ? ((Model.Page - 1) * Model.PageSize) + 1 : 1;
                var end = Model.Page != 1 ? ((Model.Page) * Model.PageSize) : Model.PageSize;
                        }
                        Showing results: @start ~ @end of @Model.TotalCount
                    </div>
                </div>
                <div class="row">
                    <nav>
                        <ul class="pager">
                            <li class="previous" id="previous"><a href="#"><span aria-hidden="true">&larr;</span>Previous</a></li>
                            <li class="next" id="next"><a href="#">Next <span aria-hidden="true">&rarr;</span></a></li>
                        </ul>
                    </nav>
                </div>
            }
            else
            {
                <div class="row">
                    <div class="col-md-12" style="text-align: center">
                        There is no data in the TB Registry. Click the Add new record link above to get started.
                    </div>
                </div>
            }

        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4" style="text-align:center">
                    <img src="~/css/images/natrapham.png" /></div>
                <div class="col-md-4" style="text-align:center">
                    <img src="~/css/images/KIDZKIT-2.png" /></div>
                <div class="col-md-4" style="text-align:center">
                    <img src="~/css/images/KIDZKIT-3.png" /></div>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="selectedMember">

<div class="modal fade" id="deleteConfirm" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div class="container" style="max-width: 500px">
                    <div class="row">
                        <div class="col-md-12">
                            <p>Are you sure you want to delete the record for</p>
                            <label id="deleteName"></label>
                            <p>
                                Note that this cannot be undone and once a record is deleted it can not be recovered.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <form action="@Url.Action("Delete")" method="post">
                        <input type="hidden" name="id" id="idToDelete" />
                        <input type="submit" class="btn btn-primary" id="deleteConfimButton" value="Delete"></input>

                        <button type="button" class="btn btn-danger" id="deleteCancel">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {

        $(".delete").on("click", function (e) {
            $("#deleteName").text($(this).data("name"));
            $("#idToDelete").val($(this).data("id"))

            $("#deleteConfirm").modal("show");
        });

        $("#deleteCancel").on("click", function (e) {
            $("#deleteConfirm").modal("hide");
        });

        $("#previous").on("click", function (e) {
            var currentPage = $("#page").val();
            if (currentPage != 1) {
                currentPage--;
            }
            $("#page").val(currentPage);
            $("#searchForm").submit();
        });

        $("#next").on("click", function (e) {
            var currentPage = $("#page").val();
            currentPage++;
            $("#page").val(currentPage);
            $("#searchForm").submit();
        });

        $(".rowdata:even").css("background-color", "rgb(245, 245, 245)")
    });
</script>